### PR TITLE
Add can io firmware

### PR DESCRIPTION
**Pull request by antoinealb**
This PR adds can-io-firmware in this subrepository and integrates with existing libraries.

edit: it does not include CI, as #13 is not resolved yet.

### CODE REVIEW

**Comment by antoinealb** [comment]
So now I integrated it into travis.

**Comment by nuft** [comment]
Do we want to squash the commits of imported repos (like with motor-control-firmware)?

**Comment by antoinealb** [comment]
What was the reason for squashing ?

**Comment by nuft** [comment]
> What was the reason for squashing ?

To not clutter up the history.
Old commits from before the import won't be useful to the main repo.

**Comment by antoinealb** [comment]
Hmmm I don't agree with that. Being able to git blame is pretty useful to understand how something ended up in that state.

**Comment by nuft** [comment]
>  Being able to git blame is pretty useful to understand how something ended up in that state.

There is no application code where history would be useful. Though, for the can-io history I don't care that much since it is not very long. 

In general, I *really* don't like having multiple histories in parallel.

**Comment by antoinealb** [comment]
Ok. How do I squash this ?

**Comment by SyrianSpock** [comment]
You can just rebase interactive and use squash/fixup and keep everything under the commit "Add 'can-io-firmware/' from commit ..."

**Pull request merged**
