### PR TITLE
Control pumps and solenoids from UAVCAN

### PR DESCRIPTION
**Pull request by antoinealb**
Tested on hardware, works.

Also added a GUI interface in studio to control the servomotors and pumps easily.

### CODE REVIEW

**Comment by nuft** [comment]
Nice GUI, works and commands are received.
But when connecting the solenoid & pump nothing moves.
@antoinealb have you also measured if PWM output is correct?

**Comment by antoinealb** [comment]
Yes I tested it, and also the power part using a lab power supply feeding on vbat. That's weird that it does not work for you

**Comment by nuft** [comment]
Ok, this must be a hardware issue then.

**Comment by nuft** [comment]
Issues came from faulty hardware. Tested for both Pump1/2 and solenoid 1/2.
Can't test servo atm but this is low risk.

**Pull request merged**
