### PR TITLE
First draft of TDMA protocol

### PR DESCRIPTION
**Pull request by antoinealb**
This pull request contains the first draft of the TMDA protocol for the UWB beacons. It is not intended to be merged as-is, but rather to serve as a discussion topic.

### CODE REVIEW

**Comment by nuft** [comment]
I quickly read through the draft and it sounds good to me.

One remark on the requirements though: It might be useful to support the fourth beacon in the center - at least for communication.

**Comment by antoinealb** [comment]
True, I forgot about the 4th beacon. Might be useful indeed, although in the worst case we could run a cable from it to a neighbor beacon that would then transmit over the air.

**Comment by SyrianSpock** [comment]
I'm fine with assuming only 3 fixed beacons are supported.

**Comment by SyrianSpock** [comment]
Would be good to support 4 fixed beacons for the landminesfree competition

**Comment by antoinealb** [comment]
4 beacon it is then. Still not satisfied with the way to send data packets though :(

**Comment by antoinealb** [comment]
Most likely never will be done

**Pull request closed without merging**
