### PR TITLE
Add DroneCI

### PR DESCRIPTION
**Pull request by antoinealb**
This pull request adds basic support for drone CI. So far it uses my custom server, but we will be able to migrate to CVRA's when we buy one.

### CODE REVIEW

**Comment by SyrianSpock** [comment]
Should probably also update the readme to show the build status of all the different firmwares/tests

**Comment by antoinealb** [comment]
Thing is you only get one badge for the whole project, not one per sub build.

**Comment by antoinealb** [comment]
But we could build our own badge server, e.g using https://github.com/gcmalloc/epfl-moodle

**Comment by SyrianSpock** [comment]
Ok, but can we at least update the current badge with the results from Drone CI ?
We can add other badges later.

**Comment by antoinealb** [comment]
Sure. Should I put my temporary server URL for the badge or we wait for the final infrastructure ?

**Pull request merged**
